In [6]:
import numpy as np
import pandas as pd

In [8]:
data=pd.read_csv("/content/diabetes.csv")

In [9]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [10]:
data.shape

(768, 9)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [12]:
data.isnull().sum()

,0
Pregnancies,0
Glucose,0
BloodPressure,0
SkinThickness,0
Insulin,0
BMI,0
DiabetesPedigreeFunction,0
Age,0
Outcome,0


In [13]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [14]:
x=data.drop(['Outcome'],axis=1)
y=data['Outcome']

In [15]:
x.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33


In [16]:
y.head()

,Outcome
0,1
1,0
2,1
3,0
4,1


In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [18]:
x_train.shape

(576, 8)

In [ ]:
x_test.shape

(192, 8)

In [ ]:
x_test.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
583,8,100,76,0,0,38.7,0.190,42
104,2,85,65,0,0,39.6,0.930,27
565,2,95,54,14,88,26.1,0.748,22
459,9,134,74,33,60,25.9,0.460,81
389,3,100,68,23,81,31.6,0.949,28


In [19]:
x_train.shape[1]

8

In [20]:
from sklearn.preprocessing import StandardScaler

In [34]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [77]:
model=keras.Sequential([
    layers.Input(shape=(x_train_scaled.shape[1],),name='input_layer'), #input_layer has 8 neurons
    layers.Dense(32,activation='relu',name='hidden_layer_1'), #hidden_layer_1 has 32 neurons
    layers.Dense(16,activation='relu',name='hidden_layer_2'), #hidden_layer_2 has 16 neurons
    layers.Dense(1,activation='sigmoid',name='output_layer') #output_layer has just 1 neuron since it is a binary classifier
])

In [78]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [90]:
model.fit(x_train_scaled,y_train,epochs=8,batch_size=16)

Epoch 1/8
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.4176   
Epoch 2/8
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.4124 
Epoch 3/8
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7986 - loss: 0.4119
Epoch 4/8
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.4049 
Epoch 5/8
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.4032 
Epoch 6/8
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8056 - loss: 0.4014 
Epoch 7/8
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8056 - loss: 0.3979 
Epoch 8/8
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8056 - loss: 0.3946 


In [91]:
y_pred_prob=model.predict(x_test_scaled)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


In [72]:
print(y_pred_prob)

[[7.32873082e-01]
 [1.94520149e-02]
 [8.74738768e-02]
 [8.25705528e-01]
 [2.32255057e-01]
 [3.44040096e-02]
 [4.88100380e-01]
 [2.38314748e-01]
 [1.18240165e-02]
 [1.43619359e-01]
 [5.90641871e-02]
 [8.13256860e-01]
 [9.03115347e-02]
 [4.07655329e-01]
 [7.96957016e-02]
 [1.16632149e-01]
 [5.20787001e-01]
 [2.38718111e-02]
 [7.61999562e-02]
 [6.94477260e-02]
 [1.13544464e-01]
 [5.38829148e-01]
 [1.60737708e-02]
 [3.29320610e-01]
 [1.04875870e-01]
 [6.10487223e-01]
 [4.72210407e-01]
 [1.56938359e-01]
 [3.21715206e-01]
 [6.00201748e-02]
 [2.69443870e-01]
 [6.11087322e-01]
 [1.51896119e-01]
 [1.75392348e-02]
 [9.07978058e-01]
 [5.21289706e-01]
 [7.66852856e-01]
 [2.31099147e-02]
 [1.10759269e-02]
 [3.46523702e-01]
 [3.54120396e-02]
 [1.12177432e-02]
 [1.02831945e-01]
 [5.85919321e-01]
 [4.02344344e-03]
 [3.08013707e-01]
 [7.03611299e-02]
 [5.51251531e-01]
 [7.53560543e-01]
 [4.93150204e-01]
 [2.37288848e-01]
 [6.78081930e-01]
 [1.99751332e-01]
 [9.62512732e-01]
 [1.30172282e-01]
 [6.305769

In [92]:
y_pred = (y_pred_prob > 0.5).astype(int)

In [67]:
print(y_pred)

[[1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]]


In [93]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [94]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.7552083333333334


In [95]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[105  12]
 [ 35  40]]
